@echo off
echo 백엔드 서버를 재시작합니다...
taskkill /F /IM python.exe 2>nul
echo 잠시 기다리세요...
timeout /t 2 /nobreak >nul
echo 서버를 시작합니다...
cd /d "C:\Users\301\mini\pro\miniProject-Team4-AICourse\backend"
python -m uvicorn app.main:app --reload --port 8000
